### PR TITLE
Bump to 3.10/3.11

### PR DESCRIPTION
**Pull request by bkerler**
Update to gnuradio 3.10 / 3.11.

### CODE REVIEW

**Comment by daniestevez** [comment]
Thanks again for taking the care to update all these!

I'm trying to understand your approach here. There is the `main39` branch which builds fine against GNU Radio 3.9 (though I haven't tested it thoroughly and I've only been using the Turbo code blocks, really). The changes from this to GNU Radio 3.10 should be small (the `firdes` -> `window` thing in the flowgraphs, and perhaps a couple things being moved to other GNU Radio in-tree module). But your changeset seems to be against master, and the changes are really large (to be expected). Why didn't you start with `maint39`?

**Comment by bkerler** [comment]
Hi Daniel, I guess due to my stupidity, lol. Right, against main39 would have been easier, usually I always merge against main or master as this should be the one people normally pull.

**Comment by daniestevez** [comment]
Can you prepare a pull request against maint39 with only the changes needed for 3.10?

**Comment by daniestevez** [comment]
Hi, since you opened this pull request, I have been using the maint39 branch under GNU Radio 3.10 without any issues. I have mainly been using the Turbo decoder and related blocks, and not the example flowgraphs. In the flowgraphs it's possible that the FIR windows will need to be updated for 3.10. I think it's worth to have the same code base for GNU Radio 3.9 and 3.10 if possible, since it simplifies maintenance.

To avoid confusion, I have created a maint-3.10 branch which for the moment points to the same commit as the maint39 branch (this is specially important because the README doesn't describe the correspondence between branches and GNU Radio versions).

**Comment by daniestevez** [comment]
Thanks by the way in taking a huge effort in updating this and many other OOTs to GNU Radio 3.10.

**Comment by bkerler** [comment]
Hi Daniel,
sorry, I didn't see your request before (too many oot ports, lol). So I'm right that this pull request can be closed now ?
Or do you still need a diff against 3.9 ?

**Comment by daniestevez** [comment]
I think it can be closed now, thanks.

**Pull request closed without merging**
